#!/usr/bin/env bash
set -e

# Set up symlink from workdir (real home) local.
ln -s /workdir/local "${HOME}"
mkdir /tmp/depmod && touch /tmp/depmod/depmod && chmod 755 /tmp/depmod/depmod
export PATH=${PATH}:/tmp/depmod

bitbake-build() {
    nice bitbake ${FB_MACHINE}-image
}
export -f bitbake-build

bash /workdir/.zinit/plugins/williamspatrick---dotfiles/files/obmc-helpers/fb-obmc-setup
